replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable"

service:
  type: ClusterIP
  port: 80

configMap:
  htmlContent: |
    <html>
      <head><title>Welcome to Platform Engineering Event</title></head>
      <body>
        <h1>Hello from ConfigMap!</h1>
        <h1>Thanks for sticking through the end of the demo</h1>
      </body>
    </html>
